### ISSUE TITLE
Application Load Error 3:0000065432

### ISSUE THREAD

**Issue by Karakth** [The-Animonculory/Modding-Resources#2]
Having Skyrim installed anywhere other than in C:/Program Files causes it to fail to launch with the above Steam error.
Skyrim will refuse to launch from anywhere (including the Stock Game folder) that isn't C:/Program Files

**Comment by Althro** [comment]
You have more serious issues with your computer if you are having issues with that.

You don't install steam or skyrim to program files as you will encounter errors.
