### ISSUE TITLE
Easier bulk Facegen

### ISSUE THREAD

**Issue by gabriel-andreescu** [The-Animonculory/Modding-Resources#5]
Hi,

Thank you for setting up this resource, it helped me understand how to generate Facegen. I did it multiple times while testing and it quickly became annoying, so I forked the synthesis patcher and excluded AstridEnd from the npcs list generated, doing that allowed me to use the "Show only active (*) forms" feature from the CK (not sure if CKPE adds it or it's from the CK itself) and simply select all the Actors, so much faster!

![image](https://github.com/The-Animonculory/Modding-Resources/assets/3175443/f6e94c09-c83e-434b-9272-756052410456)

Here's the fork if you'd want to update the guide: [https://github.com/gabriel-andreescu/Synth-NPCs-Face-Data](https://github.com/gabriel-andreescu/Synth-NPCs-Face-Data)

**Comment by Althro** [comment]
Hey, sorry I completely missed this. Thanks for the report, I'll get the guide updated with this 👍🏻
